name: Bleak Masterson
favicon: null
layout_spectrum: 0.3833300063852221
typography_spectrum: 0.22078061662614346
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7583810104988515
  lightness: 0.5994033692404628
  saturation: 0.31404590094462037
  rhythmicContrast: 0.32662481465376914
purpose: []
